host_project_id    = "tans-shared-vpc"
service_project_id = "terraform-gcp-498312"
region             = "europe-west3"
vpc_name           = "vpc-shared"
subnet_name        = "subnet-gke"
subnet_cidr        = "10.0.0.0/24"
pods_cidr          = "10.1.0.0/16"
services_cidr      = "10.2.0.0/16"
